version: "3.6"
services:

    php:
        build: .
        restart: always
        depends_on:
            - redis
            - mysql
            - mailhog
            - rabbitmq
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./log/apache2:/var/log/apache2
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SESSION_TTL=${SESSION_TTL}
            - SESSION_KEY=${SESSION_KEY}

    redis:
        image: redis:latest
        ports:
            - "6382:6379"

    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./conf:/etc/mysql/conf.d
            - ./data/dump:/docker-entrypoint-initdb.d
            - ./data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql

    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - "1025:1025"
            - "8025:8025"

    rabbitmq:
        image: rabbitmq:management
        restart: always

        container_name: rabbitmq
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        ports:
        - "5672:5672"
        - "15672:15672"

    mediawiki:
        image: mediawiki
        restart: always
        ports:
        - 8088:80
        links:
        - wikidatabase
        volumes:
        - ./wiki/images:/var/www/html/images
        # After initial setup, download LocalSettings.php to the same directory as
        # this yaml and uncomment the following line and use compose to restart
        # the mediawiki service
        - ./wiki/settings/LocalSettings.php:/var/www/html/LocalSettings.php

    # This key also defines the name of the database host used during setup instead of the default "localhost"
    wikidatabase:
        image: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=${WIKI_DB_NAME}
            - MYSQL_USER=${WIKI_DB_USER}
            - MYSQL_PASSWORD=${WIKI_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${WIKI_DB_ROOT_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - ./wiki/db:/var/lib/mysql

volumes:
    persistent: